name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21' # Укажите нужную версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Копирование в папку Лёни
      - name: Copy to vkr.leobychkov.ru
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/."
          target: "/var/www/github_deploy/data/www/vkr.leobychkov.ru"

      # TODO Создать в GitHub секреты SSH_PASSWORD и SSH_USERNAME и поменять тут
      # Копирование в папку Ромы
      - name: Copy to ymxshd.ru
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}  # Убедитесь, что хост правильный
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/."  # Копируем содержимое dist
          target: "/var/www/yxmxshd/data/www/yxmxshd.ru"